[TechDocs] Enhance PlantUML support in the techdocs container to include external puml or pu files
backstage/techdocs-container pull request #63
Opened 2023-09-28 14:28 UTC by lavanya-sainik-ericsson

I have created a pull request for the issue I have outlined on backstage. Please refer here : https://github.com/backstage/backstage/issues/20184.

[awanlin](https://github.com/awanlin) As discussed in the issue thread, looping you here as well to have a look.

2023-09-28 19:58 UTC, awanlin requested changes
Thanks again for this contribution @lavanya-sainik-ericsson, just left a couple of quick changes 👍

2023-09-28 19:58 UTC, awanlin commented on Dockerfile
> +#   When adding TechDocs with plantUml diagrams, to refer external puml or pu files in any markdown file,
```suggestion
#   When adding TechDocs with PlantUML diagrams, to refer external puml or pu files in any markdown file,
```

2023-09-28 19:58 UTC, awanlin commented on Dockerfile
> +#   eg. '!include <referencedFileName.puml>', need to include diagrams directory eg. docs in the classpath.
```suggestion
#   eg. '!include <referencedFileName.puml>', you'll need to include the diagrams directory eg. docs in the classpath.
```

2023-09-28 20:20 UTC, lavanya-sainik-ericsson commented
Hello [awanlin](https://github.com/awanlin), 

Thanks for your comments. Have done those changes. Let me know if any more corrections is needed.

2023-10-03 21:04 UTC, awanlin approved these changes
Looks good to me @lavanya-sainik-ericsson, you'll need someone from @backstage/techdocs-maintainers to review and approve, they will also do the merge

2023-10-04 10:42 UTC, lavanya-sainik-ericsson commented
Hey [awanlin](https://github.com/awanlin), 

Thanks a lot for your feedback and approval. Sure can you share how to request reviews from @backstage/techdocs-maintainers here & request their attention & valuable feedback ?

2023-10-11 18:51 UTC, johnphilip283 approved these changes
Thank you for the change - approved!

2023-10-11 18:54 UTC, merged